/**
 * Migration runner.
 *
 * Applies the SQL files generated by `drizzle-kit generate` into whichever
 * driver is active. Drizzle ships driver-specific migrators, so we dispatch on
 * the handle kind; both record applied migrations in `__drizzle_migrations`,
 * making repeated runs safe.
 */

import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { migrate as migratePglite } from 'drizzle-orm/pglite/migrator';
import { migrate as migratePostgres } from 'drizzle-orm/postgres-js/migrator';
import type { PgliteDatabase } from 'drizzle-orm/pglite';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

import { getDb } from './client.js';
import type { schema } from './schema.js';
import { logger } from '../observability/logger.js';

const here = path.dirname(fileURLToPath(import.meta.url));
export const MIGRATIONS_FOLDER = path.resolve(here, '../../drizzle');

export async function runMigrations(options: { dataDir?: string } = {}): Promise<void> {
  const handle = await getDb(options);

  if (handle.kind === 'pglite') {
    await migratePglite(handle.db as PgliteDatabase<typeof schema>, {
      migrationsFolder: MIGRATIONS_FOLDER,
    });
  } else {
    await migratePostgres(handle.db as PostgresJsDatabase<typeof schema>, {
      migrationsFolder: MIGRATIONS_FOLDER,
    });
  }

  logger.info('migrations.applied', { driver: handle.kind });
}

// Allow `pnpm db:migrate` to invoke this directly.
if (import.meta.url === `file://${process.argv[1]}`) {
  runMigrations()
    .then(() => {
      logger.info('migrations.complete');
      process.exit(0);
    })
    .catch((error: unknown) => {
      logger.error('migrations.failed', { error: String(error) });
      process.exit(1);
    });
}
